### PR TITLE
Db

### PR DESCRIPTION
**Pull request by domanteli0**
* Implemented a basic DbContext which connects to a remote sql database.
* Implemented Web API (That was on a separate branch, but I merged it to this one).
* Improved scrapers (That was also on a seperate branch, my bad).

### CODE REVIEW

**Comment by artnaxel** [comment]
Looks good, but must resolve merge conflicts first. Also, as I see, `ItemController.cs` in API is not fully implemented or you want to do it later?

**Comment by domanteli0** [comment]
> Looks good, but must resolve merge conflicts first. Also, as I see, `ItemController.cs` in API is not fully implemented or you want to do it later?

The plan was to complete the implementation later, but https://github.com/domanteli0/BlazeCart/pull/12/commits/efb3e96d333cc88246d12395240979d3129ddeb9 is completely fine for now.

**Comment by GabrieleCiurlionyte** [comment]
Database connection name should be moved to appsettings.json

**Comment by domanteli0** [comment]
> Database connection name should be moved to appsettings.json

Fixed, https://github.com/domanteli0/BlazeCart/pull/12/commits/3dee8b971b58253e2e7298e1c5de157747b94d50 does this

**Pull request merged**
